# Generated by Django 5.0.1 on 2024-02-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_txt',
            new_name='question_text',
        ),
    ]
